version: '3.7'
services:
  ui:
    build:
      context: ./frontend_streamlit
      target: final-islocaldevelopment-true

    volumes:
      - .:/workspace:cached
 
    command: /bin/sh -c "while sleep 1000; do :; done"

